### PR TITLE
Edit classification_report table

### PR DESCRIPTION
**Pull request by edgargonarr**
I found a mistake in classification_report table.

Thanks for your job.

### CODE REVIEW

**Comment by jlooper** [comment]
hi, can you tell me the thing that's being fixed here? I don't see a difference, thanks for your contribution

**Comment by edgargonarr** [comment]
> hi, can you tell me the thing that's being fixed here? I don't see a difference, thanks for your contribution

https://github.com/microsoft/ML-For-Beginners/pull/182/commits/078846d8064d7fc2453e7c69a936b342426979bf

In this suggestion, I edited the table where you display classification_report mehod. This is the only request.

Sorry, I am still learning about pull requests in github.

**Comment by jlooper** [comment]
hi, that's ok, thank you for the contribution. I just don't see where the original was broken.

**Comment by edgargonarr** [comment]
> hi, that's ok, thank you for the contribution. I just don't see where the original was broken.

image

In line 220, column labels must be one cell to the right.

**Comment by jlooper** [comment]
Looks like some of the other tables need fixing, let me explore, thank you!

**Pull request merged**
