### PR TITLE
typo in Readme

### PR DESCRIPTION
**Pull request by amitbatra31**
transformed_feature_df instead of transformed_df

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
hi, can you review the code in /solution and make these changes, make sure it runs, and add edits to this PR? Thanks for the catch!

**Review by Rishit-dagli — APPROVED** [review]
Ah this makes sense as shown earlier in the README:

```python
oversample = SMOTE()
transformed_feature_df, transformed_label_df = oversample.fit_resample(feature_df, labels_df)
```

**Comment by Rishit-dagli** [comment]
> hi, can you review the code in /solution and make these changes, make sure it runs, and add edits to this PR? Thanks for the catch!

I noticed the solution does not have this typo it uses `transformed_feature_df` itself.

**Comment by amitbatra31** [comment]
Checking the solution I think this code is missing in readme which resolves the typo
`transformed_feature_df.head()`
`transformed_df = pd.concat([transformed_label_df,transformed_feature_df],axis=1, join='outer')`
`transformed_df`

**Comment by Rishit-dagli** [comment]
> Checking the solution I think this code is missing in readme which resolves the typo
> `transformed_feature_df.head()`
> `transformed_df = pd.concat([transformed_label_df,transformed_feature_df],axis=1, join='outer')`
> `transformed_df`

As I understand the goal of this piece of code is to take a look at the features, so this addition wouldn't be required, what do you think?

**Comment by jlooper** [comment]
I think you're right, Amit. That code is missing in the README, let me add it in and close this PR. That's important code because it creates a fresh dataframe that is finally saved into a csv.

**Comment by jlooper** [comment]
closing, thanks for this catch

**Pull request closed without merging**
