### PR TITLE
Fixed hyperlinks and knitted the Rmd files to html for beginning half of the repo

### PR DESCRIPTION
**Pull request by jasleen101010**
- Knitted lesson 1,2,3,4,10 from Rmd to html
- Fixed hyperlinks wherever required in the repo

### CODE REVIEW

**Comment by BBKOOKE** [comment]
1

**Review by carlotta94c — CHANGES_REQUESTED** [review]
Hi @jasleen101010, huge thanks for your PR! This looks great overall, can you just ignore .Rdata, .Rhistory and .Rproject file and then commit again? Thanks!

**Comment by jasleen101010** [comment]
> 

@carlotta94c Done as requested!

**Comment by carlotta94c** [comment]
Hey @jasleen101010 they are still tracked in the PR. It happens when you do gitignore after you push, since the files are already in the index. You should clean your cache, try 'git rm --cached <filepath>'. Look at the git doc https://git-scm.com/docs/git-rm.

**Comment by jasleen101010** [comment]
> Hey @jasleen101010 they are still tracked in the PR. It happens when you do gitignore after you push, since the files are already in the index. You should clean your cache, try 'git rm --cached {filepath}'. Look at the git doc https://git-scm.com/docs/git-rm.

Hi @carlotta94c . I think it has been fixed now as we discussed. Do let me know if anything else needs to be done from my end. Thanks.

**Comment by carlotta94c** [comment]
> > Hey @jasleen101010 they are still tracked in the PR. It happens when you do gitignore after you push, since the files are already in the index. You should clean your cache, try 'git rm --cached {filepath}'. Look at the git doc https://git-scm.com/docs/git-rm.
> 
> Hi @carlotta94c . I think it has been fixed now as we discussed. Do let me know if anything else needs to be done from my end. Thanks.

I am sorry, just a quick one. Can you ignore also ML-For-Beginners.Rproj? Also, in the gitignore file you have .Rproj.user
mentioned twice.

**Review by carlotta94c — APPROVED** [review]

**Pull request merged**
