### PR TITLE
further HORIZON+1 fixes 

### LINKED ISSUE #291: Timeseries - ARIMA notebook can't compare predictions to actual load
**Describe the bug**
While making predictions on the test data, a `ValueError` is raised by pandas because the indexes don't match the length of values:

```
ValueError: Length of values (46) does not match length of index (45)
```

**To Reproduce**
1. Open https://github.com/microsoft/ML-For-Beginners/blob/main/7-TimeSeries/2-ARIMA/solution/notebook.ipynb
2. Run all cells until cell 19 _"Compare predictions to actual load"_
3. See error

**Expected behavior**
There is no exception raised

**Screenshots**
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/nk/r3v6ztqj761035fb_f59wd8m0000gn/T/ipykernel_81494/2465955293.py in <module>
      1 eval_df = pd.DataFrame(predictions, columns=['t+'+str(t) for t in range(1, HORIZON+1)])
----> 2 eval_df['timestamp'] = test.index[0:len(test.index)-HORIZON+1]
      3 eval_df = pd.melt(eval_df, id_vars='timestamp', value_name='prediction', var_name='h')
      4 eval_df['actual'] = np.array(np.transpose(test_ts)).ravel()
      5 eval_df[['prediction', 'actual']] = scaler.inverse_transform(eval_df[['prediction', 'actual']])

~/miniforge3/envs/tmp/lib/python3.8/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   3605         else:
   3606             # set column
-> 3607             self._set_item(key, value)
   3608 
   3609     def _setitem_slice(self, key: slice, value):

~/miniforge3/envs/tmp/lib/python3.8/site-packages/pandas/core/frame.py in _set_item(self, key, value)
   3777         ensure homogeneity.
   3778         """
-> 3779         value = self._sanitize_column(value)
   3780 
   3781         if (

~/miniforge3/envs/tmp/lib/python3.8/site-packages/pandas/core/frame.py in _sanitize_column(self, value)
   4502 
   4503         if is_list_like(value):
-> 4504             com.require_length_match(value, self.index)
   4505         return sanitize_array(value, self.index, copy=True, allow_2d=True)
   4506 

~/miniforge3/envs/tmp/lib/python3.8/site-packages/pandas/core/common.py in require_length_match(data, index)
    529     """
    530     if len(data) != len(index):
--> 531         raise ValueError(
    532             "Length of values "
    533             f"({len(data)}) "

ValueError: Length of values (46) does not match length of index (45)
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OS X M1, but same behavior using Azure compute resource

**Additional context**
Using Python 3.8.
The problem happens in this line in particular:
```python
eval_df['timestamp'] = test.index[0:len(test.index)-HORIZON+1]
```
I don't really understand the underlying issue, but tried making changes to the `HORIZON+1` part of it to see if I could align to the expected number. 

With `+0`: `ValueError: 2 columns passed, passed data had 3 columns`
With `+2`: `ValueError: 4 columns passed, passed data had 3 columns`

### PR DESCRIPTION
**Pull request by alfredodeza**
After adding the previous change (fixed in https://github.com/microsoft/ML-For-Beginners/issues/165) it caused ARIMA's solution notebook to no longer work and break with an exception from Pandas.

I don't feel super confident about this PR except for the fact that the notebook now works with same/similar output to the previous one.

Fixes #291

### CODE REVIEW

**Review by jlooper — COMMENTED** [review]
I'd love @FrancescaLazzeri to add thoughts here as the expert

**Comment by jlooper** [comment]
@shwars could we get your opinion here?

**Comment by shwars** [comment]
@jlooper @alfredodeza after quickly looking at the code it seems to me that `yhat = model_fit.forecast(steps = HORIZON)` is a better option, because for `HORIZON=1` it will make a forecast for 1 step, which seems logical.

**Comment by alfredodeza** [comment]
> @jlooper @alfredodeza after quickly looking at the code it seems to me that `yhat = model_fit.forecast(steps = HORIZON)` is a better option, because for `HORIZON=1` it will make a forecast for 1 step, which seems logical.

The problem we are hitting is that because we've used `HORIZON+1` creating `test_shifted` then nothing fits anymore. I couldn't find a way to make the playbook work without `yhat = model_fit.forecast(steps = HORIZON+1)` and the other changes. 

Then again, not because it works now it means it is correct :D 

I'm happy to modify as needed. Not entirely sure. what the right path is here.

**Comment by jlooper** [comment]
> > @jlooper @alfredodeza after quickly looking at the code it seems to me that `yhat = model_fit.forecast(steps = HORIZON)` is a better option, because for `HORIZON=1` it will make a forecast for 1 step, which seems logical.
> 
> The problem we are hitting is that because we've used `HORIZON+1` creating `test_shifted` then nothing fits anymore. I couldn't find a way to make the playbook work without `yhat = model_fit.forecast(steps = HORIZON+1)` and the other changes.
> 
> Then again, not because it works now it means it is correct :D
> 
> I'm happy to modify as needed. Not entirely sure. what the right path is here.

Should we return to the original `HORIZON`? This was where we started

**Review by Shujasheikh — COMMENTED** [review]
This is good stuff to learn plus allow me to join....

**Comment by bluetonnz337** [comment]
# - [ ] []()@_**~~~~**_

**Comment by jlooper** [comment]
I decided to roll back the example to Francesca's original, to stop errors

**Pull request closed without merging**
