### PR TITLE
feat: add ja Base README

### PR DESCRIPTION
**Pull request by Foo-x**
Refs #149

Add Japanese translation of the base README.

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
hi, please ensure that all paths are properly linked (you may need to add `../` to get a good relative paths for images and lessons.  Also can you please identify a linguistic reviewer?

thank you!

**Comment by Foo-x** [comment]
Thank you for your review!

I reffered the [README of Web-Dev-For-Beginners](https://github.com/microsoft/Web-Dev-For-Beginners/commit/0b114230b9afa1cfc55075c92de19454fefe9cfe#diff-2373fedca398d1e5c573e16e826ea6d2818d547b9ce06e068ad2e7566ed227c2R44), but it seems to work only in GitHub, so I have fixed as you said.

@kenya-sk , since you seem to have committed the most lines of Japanese translations in this repo, could you please review this?

**Comment by kenya-sk** [comment]
Of course. I will do a linguistic review.

**Comment by kenya-sk** [comment]
I checked the contents. There was no linguistic problem. 
Thank you for your hard work!

**Review by jlooper — APPROVED** [review]

**Pull request merged**
