### PR TITLE
translated 2-Regression/Readme.md into simplified Chinese

### PR DESCRIPTION
**Pull request by loap-a**

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
hi, could you rename this file to README.zh-ch.md please, and the links should point to the localized Regression lesson files. thanks!

**Comment by loap-a** [comment]
sorry about the mistakes. I have changed those.

**Review by jlooper — CHANGES_REQUESTED** [review]
oh! just noticed one more edit to make: the title of the file should be README.zh-cn.md. Sorry if I messed that up.

thanks!

**Comment by loap-a** [comment]
this should be ok.  sorry about the mistakes again.

**Review by jlooper — APPROVED** [review]

**Pull request merged**
