### PR TITLE
Create README.zh.md

### PR DESCRIPTION
**Pull request by XiaojianTang**
Initial update of Chinese translation

### CODE REVIEW

**Comment by XiaojianTang** [comment]
> [CLA assistant check](https://cla.opensource.microsoft.com/microsoft/ML-For-Beginners?pullRequest=164)
> All CLA requirements met.

**Comment by feiyun0112** [comment]
> Initial update of Chinese translation

文件名改一下，简体中文是`README.zh-cn.md`

**Comment by XiaojianTang** [comment]
> > Initial update of Chinese translation
> 
> 文件名改一下，简体中文是`README.zh-cn.md`
> 
> 链接的相对路径也要改，比如(1-intro-to-ML/README.md)改成(../1-intro-to-ML/translations/README.zh-cn.md)

已修改，谢谢

**Comment by feiyun0112** [comment]
还有图片的相对路径

**Review by jlooper — CHANGES_REQUESTED** [review]
Hi, please edit image paths so images will show, thank you!

**Comment by XiaojianTang** [comment]
> Hi, please edit image paths so images will show, thank you!

Sorry, missed it. I have update the path, please check, Thanks

**Review by jlooper — APPROVED** [review]

**Pull request merged**
