### PR TITLE
R resources for lesson 11: Introduction to classifiers

### PR DESCRIPTION
**Pull request by R-icntay**
- Added artwork: _parsnip.jpg_
- Added R Notebooks: _lesson_11-R.ipynb, lesson_11.Rmd_

### CODE REVIEW

**Review by jlooper — APPROVED** [review]

**Review by jlooper — CHANGES_REQUESTED** [review]
hi, since I've redone the folder structure, do you mind moving this over to the R folder - image paths might need editing too

**Comment by R-icntay** [comment]
Working on it Jen

**Comment by R-icntay** [comment]
Jen, I think we are all good now.

**Review by jlooper — APPROVED** [review]
today's new word of the day is 'tibble' :) not to be confused with 'tribble' from Star Trek

**Comment by ravindranath-sawane** [comment]
Same I  thought that is "tribble"  @jlooper  ;)

**Pull request merged**
