### PR TITLE
updated column for R #317

### PR DESCRIPTION
**Pull request by priyankkhanna**
will this work?

### CODE REVIEW

**Comment by priyankkhanna** [comment]
haven't added link as right now i am not aware of the appropriate link

**Comment by priyankkhanna** [comment]
markdown files for R lessons are named as .Rmd. Shouldn't they be R.md?

**Review by jlooper — CHANGES_REQUESTED** [review]
Hi, this is better, but looks odd on mobile. Can you add bullets:

- Python
- R

if there are no R lessons, let’s not include the link. If there are, you can link to the R lesson notebook which are in /solution/R - they start in the Regression  lesson area. 

Also, let’s add the author credit in the last column: Eric Wanjau (R) if there is a lesson. 

Thank you! And thanks @alfredodeza for the guidance too - a better solution than more columns!

**Comment by priyankkhanna** [comment]
on it

**Comment by priyankkhanna** [comment]
will this work? @jlooper

**Review by jlooper — CHANGES_REQUESTED** [review]
hi, looking at the markup, two changes please:

You can create bullets in markdown by using `-` rather than adding html, so let's edit out the `<ul> and <li>` to simplify the markdown.

The last lesson should be listed as 'lesson' (Real World) as there's no code associated to that lesson.

**Comment by priyankkhanna** [comment]
I tried using - but it is not working properly inside table that's why I switched to html.
In table - is not doing well. 
| Tables        | Are           |
| ------------- |:-------------:|
| col 3 is      | - first - second |
| col 2 is      | centered      |

| Tables        | Are           |
| ------------- |:-------------:|
| col 3 is      | - first 
- second |
| col 2 is      | centered      |

**Review by jlooper — APPROVED** [review]

**Pull request merged**
