### PR TITLE
[WIP] Translate assignments and quizzes to Korean

### PR DESCRIPTION
**Pull request by ianikpark**
### 1. Introduction

- [x] [1.1. Intro to ML](https://github.com/ianikpark/ML-For-Beginners/commit/873fe7d3ad67f738d7b03e141319c2cde7c54a9d)
- [x] [1.2. History of ML](https://github.com/ianikpark/ML-For-Beginners/commit/b522bd633fe1f3eff5b5e8f9a0da80c8f6e4ba1e)
- [x] [1.3. Fairness](https://github.com/ianikpark/ML-For-Beginners/commit/935ca4bb9d087ec97511337e4f79b93d7132aa79)
- [x] [1.4. Techniques of ML](https://github.com/ianikpark/ML-For-Beginners/commit/b440330b897630d3ea19ee0f251391d62863e99b)

### 2. Regression
- [x] [2.1. Tools](https://github.com/ianikpark/ML-For-Beginners/commit/6466d635a01207f47ce0fbfeeeefa2115d872a82)
- [x] [2.2. Data](https://github.com/ianikpark/ML-For-Beginners/commit/5bf3014726e59d803f1502ff7ab966de579d4daf)
- [x] [2.3. Linear](https://github.com/ianikpark/ML-For-Beginners/commit/8d8a0688d82b437feece754153bf663c708fa4f5)
- [x] [2.4. Logistic](https://github.com/ianikpark/ML-For-Beginners/commit/2862feb0b52be3177b7ed6030e27ce97b6fe563a)

### 3. Web App
- [x] [3.1. Web App](https://github.com/ianikpark/ML-For-Beginners/commit/079f33700c6da3d78d1281b232ba7f7a7558bb64)

### 4. Classification
- [x] [4.1. Introduction](https://github.com/ianikpark/ML-For-Beginners/commit/7e51a273cdbeb5699a2d9337e15aa19f1fd317f1)
- [x] [4.2. Classifiers 1](https://github.com/ianikpark/ML-For-Beginners/commit/b68b134cfb954a9250bda9165009c4084d1294c1)
- [x] [4.3. Classifiers 2](https://github.com/ianikpark/ML-For-Beginners/commit/c49b6339481ec799cca2dbcaaf988b724ad8573a)
- [x] [4.4. Applied](https://github.com/ianikpark/ML-For-Beginners/commit/65504f0b9e2014709e10ca94e456c2b2163a0ec8)

### 5. Clustering
- [x] [5.1. Visualize](https://github.com/ianikpark/ML-For-Beginners/commit/6d67fd73cc3f5c7b9a91ec98f1dea6099c37a9ec)
- [x] [5.2. K-Means](https://github.com/ianikpark/ML-For-Beginners/commit/e0b44be8d0592bb35735dc7e397c487f8dbcd0aa)

### 6. NLP
- [x] [6.1. Introduction to NLP](https://github.com/ianikpark/ML-For-Beginners/commit/41f36b6b14121d9ae34a9276971c093eacc139f8)
- [x] [6.2. Tasks](https://github.com/ianikpark/ML-For-Beginners/commit/5c003c682fb82f28501ff147ea0aeeeec6e99c82)
- [x] [6.3. Translation Sentiment](https://github.com/ianikpark/ML-For-Beginners/commit/c31c04080f8d3c27bff957dfac9c931dc1536bc4)
- [x] [6.4. Hotel Reviews 1](https://github.com/ianikpark/ML-For-Beginners/commit/a7cfb08ae027a50a1dab90f05b31aac90767ac8b)
- [x] [6.5. Hotel Reviews 2](https://github.com/ianikpark/ML-For-Beginners/commit/6664c6059cda4053cc6ee173e8da29b410904dd0)

### 7. Time Series
- [x] [7.1. Introduction](https://github.com/ianikpark/ML-For-Beginners/commit/8b95151334cca4c2609ee8c691ede322cb337525)
- [x] [7.2. ARIMA](https://github.com/ianikpark/ML-For-Beginners/commit/4c50ec6811491c67198331b77d7ce5c2a012069a)

### 8. Reinforcement
- [x] [8.1. Q-Learning](https://github.com/ianikpark/ML-For-Beginners/commit/00abaa5623b4469f251ddd9b694e0b9c620bee03)
- [x] [8.2. Gym](https://github.com/ianikpark/ML-For-Beginners/commit/0c1b2b073abc9b48c8cf99641fdb2668b25dc195)

### 9. Real World
- [x] [9.1. Applications](https://github.com/ianikpark/ML-For-Beginners/commit/730835c9b906eeac8ff54cb5e255c60695700c83)

## Quizzes

- ~~Quizzes~~ to be delivered separately

### CODE REVIEW

**Comment by jung-youjin** [comment]
@ianikpark Hi there! I'm impressed by your hard work 👍🏼 I'd like to support you and contribute as well to [9. Real World assignment](https://github.com/microsoft/ML-For-Beginners/blob/main/9-Real-World/1-Applications/assignment.md) and partially on [Quizzes](https://github.com/microsoft/ML-For-Beginners/blob/main/quiz-app/src/assets/translations/en.json) if you don't mind. Would that be fine? 😄

**Comment by ianikpark** [comment]
> @ianikpark Hi there! I'm impressed by your hard work 👍🏼 I'd like to support you and contribute as well to [9. Real World assignment](https://github.com/microsoft/ML-For-Beginners/blob/main/9-Real-World/1-Applications/assignment.md) and partially on [Quizzes](https://github.com/microsoft/ML-For-Beginners/blob/main/quiz-app/src/assets/translations/en.json) if you don't mind. Would that be fine? 😄

Hi @jung-youjin,

Thanks for asking. As I'm close to finishing translating the assignments, I'd personally like to wrap them all up by myself to keep the consistency of translation across all as much as possible. You're more than welcome to take the quizzes, though -- I'd appreciate your hand (having kind of busy days right now 😅). Thanks.

**Comment by jlooper** [comment]
So close!! Would love to ship - should we ship without the quizzes, maybe take those as part 2?

**Comment by ianikpark** [comment]
> So close!! Would love to ship - should we ship without the quizzes, maybe take those as part 2?

Sure!

PS I need just a few more days to finish the quizzes. They should be ready soon! I'll create a separate draft pull request for the quizzes.

**Review by jlooper — APPROVED** [review]
thank you so much!

**Pull request merged**
