### PR TITLE
Added ml.gif

### PR DESCRIPTION
**Pull request by mohitjaisal**
- Added ml.gif to readme .md 
- The gif is fully compressed and load very fast

Suggested by @jlooper [Merged PR](https://github.com/microsoft/Data-Science-For-Beginners/pull/221#issuecomment-954939774)

## Before:
image

## After:
image

### CODE REVIEW

**Comment by mohitjaisal** [comment]
@jlooper , @kant  please review !!

**Comment by jlooper** [comment]
So awesome! Thank you!!

**Review by jlooper — APPROVED** [review]
I’ll add a credit too!

**Comment by mohitjaisal** [comment]
Thanks a lot @jlooper for the quick review !! 😊

**Pull request merged**
