### PR TITLE
propose Regression french translation readme

### PR DESCRIPTION
**Pull request by ManuSquall**
add a README.fr.md for Regression base README

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
ouais! les citrouilles (one of my favorite french words).

I think you probably should go ahead and change the links to the localized README files proactively. 

merci!

**Comment by ManuSquall** [comment]
Is it okay like this please @jlooper ? :


image


I have update the links for the future translation files. 👀

**Comment by ManuSquall** [comment]
Or should i do like loap-a has done? :

image

**Comment by jlooper** [comment]
> Is it okay like this please @jlooper ? :
> 
> image
> 
> I have update the links for the future translation files. 👀

this looks right to me. All the translated files should reference each other in the lessons. thanks!

**Review by jlooper — APPROVED** [review]
ouais!

**Pull request merged**
