### PR TITLE
Solution to issue 543

### PR DESCRIPTION
**Pull request by Richa2801**
Added new file OpenForce.ipynb in ML-For-Beginners

### CODE REVIEW

**Comment by Richa2801** [comment]
Contribution to issue #543

**Comment by jlooper** [comment]
This PR does not follow the requirements of the repo, but the solution might be attached to the issue as a partial solution

**Comment by Richa2801** [comment]
> This PR does not follow the requirements of the repo, but the solution might be attached to the issue as a partial solution

Hello, can I make any changes to this PR so that it can be merged instead of being closed? Can you pls suggest what changes I should make?

**Comment by jlooper** [comment]
hi, there's a considerable amount that needs to be changed, including editing the lesson, following our standard curricular format. Adding a new file with a solution is not needed; the lesson needs editing with a clear explanation as we are discussing in #543

**Comment by Richa2801** [comment]
> hi, there's a considerable amount that needs to be changed, including editing the lesson, following our standard curricular format. Adding a new file with a solution is not needed; the lesson needs editing with a clear explanation as we are discussing in #543
> 
> I will add that we are getting spammed by low-quality submissions by this Open Force initiative and I am not likely to merge content unless it adheres to our quality standards.

Okay, thanks

**Pull request closed without merging**
