### PR TITLE
bangla translation added

### PR DESCRIPTION
**Pull request by mamutalib**
I have added a short portion of Bangla translation of Introduction of Machine Learning.

### CODE REVIEW

**Review by jlooper — COMMENTED** [review]
hi, I will convert this to a draft so that the translation can be completed

**Comment by mamutalib** [comment]
> hi, I will convert this to a draft so that the translation can be completed

Thanks for your quick response. I will complete full translation as soon as possible for me.

**Review by jlooper — CHANGES_REQUESTED** [review]
hi, let's translate all the pieces, please, and make sure paths are correct

**Review by mamutalib — COMMENTED** [review]
I have added a complete Bangla translation of  Introduction/1-intro-to-ML page.

**Pull request closed without merging**
