### PR TITLE
Audit 2.0

### PR DESCRIPTION
**Pull request by ravindranath-sawane**
Chaged 'tibble' to 'table'

### CODE REVIEW

**Comment by alfredodeza** [comment]
Can you update your PR to have something more descriptive than _Audit 2.0_ ? This will help us identify PRs better today, and refer to them in the future. Thanks!

**Comment by alfredodeza** [comment]
Is this PR different than the one I just merge (#311) ?

**Comment by ravindranath-sawane** [comment]
@alfredodeza The file updated in this Audit is 4-Classification/1-Introduction/solution/lesson_10.Rmd  in Earlier Audit the File was Different

**Comment by ravindranath-sawane** [comment]
Sorry for 2 different PR's

**Comment by jlooper** [comment]
Turns out..... 'tibble' is the correct verbiage!! see the discussion board... who knew!

**Pull request closed without merging**
