### PR TITLE
Add Turkish translation of the base README.md file

### PR DESCRIPTION
**Pull request by buseorak**

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
hello, thank you! Can you edit the image paths so that they will show, and also ensure that all the lesson paths are correct (you will probably have to add `../`)

thanks!

**Review by jlooper — APPROVED** [review]
thank you!

**Comment by buseorak** [comment]
@jlooper Thank you sincerely for guiding me in my first PR here! :)

**Comment by jlooper** [comment]
> @jlooper Thank you sincerely for guiding me in my first PR here! :)

It’s my pleasure! 🙏🎉❤️

**Pull request merged**
